### ISSUE TITLE
No Response from localhost:161

### ISSUE THREAD

**Issue by gregorleban** [fboaventura/dckr-mrtg#20]
I have ran the following commands on my Debian in an empty folder:

```
mkdir html conf.d
docker run -d -p 8880:80 -e "HOSTS='public:localhost,community:ipaddress'" -v `pwd`/html:/mrtg/html -v `pwd`/conf.d:/etc/mrtg/conf.d fboaventura/dckr-mrtg:latest
```

After the docker image starts, I am not able to open the localhost:8880. 

If I run the `docker logs name_of_the_container` I get the following output:

```
usermod: no changes
Timeout: No Response from localhost:161
```

Any idea what is wrong and why am I not able to see the page on 8880? Do I need to set up any other configuration or data before running docker image?

Thank you in advance for any help!

**Comment by fboaventura** [comment]
@gregorleban, can you ensure you have the SNMP daemon running on localhost?

In the `HOSTS` variable, you must pass the `community` and `ipaddress` of the SNMP-enabled hosts you want to monitor, separated by commas.

With the command you passed, you are trying to monitor two servers, one running on the `localhost` with the community `public` and the other running at `ipaddress` with the community `community`.

You may try using the following `docker-compose.yml` to get it running on your local machine. This will spin a SNMP server container and the MRTG, listening on port `8880`:

```docker-compose
version: "3.5"

services:
  snmpd:
    image: really/snmpd
    privileged: yes
    volumes:
      - "/proc:/host_proc:ro"
      - ./snmpd.conf:/etc/snmp/snmpd.conf
    ports:
      - "161:161/udp"
    hostname: snmpd
  mrtg:
    image: fboaventura/dckr-mrtg:2.5.3
    hostname: mrtg
    restart: always
    ports:
      - "127.0.0.1:8880:80"
    volumes:
      - "./conf.d:/etc/mrtg/conf.d"
      - "./html:/mrtg/html"
    environment:
        TZ: "Brazil/East"
        HOSTS: "public:snmpd"
    tmpfs:
      - "/run"
```

You will also need the `snmpd.conf` file below in the same folder:

```conf
# Change "public" on the line below to your preferred SNMP community string
com2sec readonly  default         public

group MyROGroup v2c        readonly
view all    included  .1                               80
access MyROGroup ""      any       noauth    exact  all    none   none

syslocation HomeLab
syscontact HomeLab Support <support@example.org>

```
