### ISSUE TITLE
group mrtg views per host

### ISSUE THREAD

**Issue by vasylherman** [fboaventura/dckr-mrtg#5]
Hello, I have 25 hosts monitoring
I'd like your container to create a web-dir per host in "/mrtg/html"
/mrtg/html/10.10.10.1
/mrtg/html/10.10.10.2
/mrtg/html/10.10.10.3

Is that possible?
I'd appreciate any help

**Comment by fboaventura** [comment]
@PrettySolution according to MRTG [documentation](https://people.cs.rutgers.edu/~terminals/mrtg/mrtg-2.5.4c/mrtg-conf.html#Directory) it is possible to achieve what you want, but it beats the purpose of this container.

You would have to add a `Directory` directive to each host you want to use a different folder.  The folder must reside under the `WorkDir` and must be manually created. MRTG won't create the folders.
